name: Markdown Lint
on:
  push:
    branches:
      - main
    paths:
      - '**/*.md'
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v4

      - name: Install Node
        id: install-node
        uses: actions/setup-node@v6

      - name: Install Markdownlint cli
        id: install-markdownlint-cli
        run: npm install markdownlint-cli2 --global

      - name: Run Linting
        id: run-markdownlint
        run: markdownlint-cli2 "**/*.md" "#node_modules" --config ./.markdownlint-cli2.yaml