name: Wiki Linting
on:
  gollum:

  workflow_dispatch:

jobs:
  lint-wiki:
    name: Lint wiki
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        id: clone-repository
        run: |
          git clone https://github.com/${{ github.repository }}.wiki.git wiki
          cd wiki
          ls -la